TRAIN:
  train_batch_size: 32
  lr: 0.001

  valid_batch_size: 8

  image_size: [224,224]

  min_epochs: 15
  max_epochs: 15
  patience: 10000

  device: 1

  model_save_path: ./save_model_mos_b32_0001
  model_save_filename: medseg

MODEL:
  bert_type: microsoft/BiomedVLP-CXR-BERT-specialized
  vision_type: None
  project_dim: 768

DATA:
  train_csv_path: /mnt/data1/RIS/QaTa-COV19/QaTa-COV19-v2_backup/Train_text_for_Covid19.xlsx
  train_root_path: /mnt/data1/RIS/QaTa-COV19/QaTa-COV19-v2_backup/Train

  test_csv_path: /mnt/data1/RIS/QaTa-COV19/QaTa-COV19-v2_backup/Test_text_for_Covid19.xlsx
  test_root_path: /mnt/data1/RIS/QaTa-COV19/QaTa-COV19-v2_backup/Test

#
#DATA:
#  train_csv_path: /mnt/data1/RIS/Train_text_MosMedData+ 1.xlsx
#  train_root_path: /mnt/data1/RIS/MosMedData
#
#  val_csv_path: /mnt/data1/RIS/Val_text_MosMedData+ 1.xlsx
#  val_root_path: /mnt/data1/RIS/MosMedData
#
#  test_csv_path: /mnt/data1/RIS/Test_text_MosMedData+.xlsx
#  test_root_path: /mnt/data1/RIS/MosMedData


# CUDA_VISIBLE_DEVICES=1  python train.py
# tsp python train.py